### ISSUE TITLE
Ensure backward compatibility of PSE

### ISSUE THREAD

**Issue by ginihumer** [jku-vds-lab/projection-space-explorer-app#1]
when trying to open the first chess games dataset the app crashes with this error: 

![Image](https://user-images.githubusercontent.com/45741696/224036659-49a875c0-5ff6-4c81-b8dc-8ea8bc6653ac.png)

how to link PSE during development? 
error when trying with "npm link":

![Image](https://user-images.githubusercontent.com/45741696/224029470-d3ebed75-f73f-46b2-aa27-a9538d9791da.png)

-> add description to README

**Comment by dvmoritzschoefl** [comment]
@ginihumer this was probably an old deployment. The current pse works just fine with every dataset I tried.

Regarding the linking, that is dependend on the tech stack of the consuming app. So a different approach might be needed depending on wether webpack 4/5 is used or npm/yarn
