### ISSUE TITLE
Define groups by clustering does not work

### ISSUE THREAD

**Issue by jzethofer** [jku-vds-lab/projection-space-explorer-app#3]
![image](https://github.com/jku-vds-lab/projection-space-explorer-app/assets/98895743/80493d0e-6e9b-4568-b426-9e7cb04b6d79)

**Comment by keckelt** [comment]
The baseUrl for the backend is not set.

It can be based via props of the PSE application: https://github.com/jku-vds-lab/projection-space-explorer/blob/develop/src/Application.tsx#L103-L113

I.e., in https://github.com/jku-vds-lab/projection-space-explorer-app/blob/main/src/App.tsx#L149
