### ISSUE TITLE
Search field for projection feature selection

### ISSUE THREAD

**Issue by jzethofer** [jku-vds-lab/projection-space-explorer-app#8]
- add a search field for finding features in datasets with many features
![image](https://github.com/jku-vds-lab/projection-space-explorer-app/assets/98895743/b064b206-b143-4341-84fb-70a44f1ba705)

**Comment by Aystein** [comment]
I am not sure if this is trivial. https://adazzle.github.io/react-data-grid/#/header-filters would have to support this (with grouping)
